Pin package versions to make this project runnable again
gandroz/rl-taxi pull request #1
Opened 2023-01-15 11:59 UTC by FieteO

Currently this project does not have any version pinning for it's python version and dependencies. Accordingly, when setting up a new virtual env with the latest version of it's dependencies, the project is not runnable since there were breaking changes in the meantime.

This PR 
- pins the versions based on `pipenv`
- creates the `models` output folder when initially invoking the script
- adds a 'Getting started' section in the README that describes the necessary setup

2023-01-15 15:06 UTC, gandroz requested changes
Thanks for your valuable PR ! This project was not meant to be improved, but why not ! I appreciate you are interested by this toy project.
Cheers !

2023-01-15 15:06 UTC, gandroz commented on pytorch/agent.py
> +        self.model_dir = './models'
you could have used a pathlib.Path instead

2023-01-15 19:02 UTC, FieteO commented
You know, it's just a shame when an example becomes unusable. I don't plan to contribute more than that :D

2023-01-17 18:44 UTC, FieteO commented
Anything else to do on my side, or can this be merged?

2023-01-17 18:51 UTC, merged